### ISSUE TITLE
Mark homework 1, exercise 2 of William-Morton

### ISSUE THREAD

**Issue by mortonwilliam** [mortonwilliam/stat679work#1]
623578e
@cecileane 
hi, i'm ready `some code` 

``` shell
a  big block of code
```

**done**!

**Comment by cecileane** [comment]
Hi William,

Great work! I hope you are proud of all that you learned, and I hope that it will be useful for your research in the next few years.

Your normalization script is lean and simple: that's great.
Your summarizing script is also well written, easy to read, and very well commented. Great job. Some feedback below that might be helpful in the future:
- you have many things in this file that have been commented out, from earlier trial. Once you are happy with your script, you should remove these earlier attempts (lines 1-38 ad lines 54-55, from [here](https://github.com/mortonwilliam/stat679work/blob/v1.2/coursedata/hw1-snaqTimeTests/summarizeSNaQres.sh)). It would make for an easier-to-read script in the end.
- when I ran your script it ran just fine (yeah!) but there was a lot of unnecessary screen output, which might seem like suspicious for someone else than you (is that an error? is that normal?). More specifically, this is what I got:

``` shell
$ bash summarizeSNaQres.sh
Filename, Hmax, CPU Time, main seed
my filename is out/bT1.out
Filename, Hmax, CPU Time, main seed
my filename is out/net1_snaq.out
Filename, Hmax, CPU Time, main seed
my filename is out/newtry1.out
Filename, Hmax, CPU Time, main seed
my filename is out/timetest01_snaq.out
Filename, Hmax, CPU Time, main seed
...
my filename is out/timetest13_snaq.out
Filename, Hmax, CPU Time, main seed
```

The repeating of `Filename, Hmax, CPU Time, main seed` is unexpected, and you could avoid it by removing line 57 (and 40) in your script.
- format: there should be **no spaces** in a csv file, to respect the csv format. Commas are used to separate columns: not spaces. If you have a space after a comma, this space is interpreted as being part of the value in the next column, which is typically not desired. More specifically, this line in the output file: `bT1, 0, 103354.760381735` should instead be written like this: `bT1,0,103354.760381735` (no spaces). To get this, it's as simple as removing the spaces in your `echo` command that writes to the output file.
  Your output file should also have a **header**, with the name of the columns (analysis, h and CPUtime), again separated by commas and no spaces.
- finally, when I executed your script, it added 16 more lines to the output file, making this file twice as long as it should be. The script should start by erasing whatever content was in the file (perhaps when writing the header), and then append. If the script appends only, then the file can grow and grow and grow if the script is run multiple times. It's best to prevent that.

regarding git and documentation:
- it would be great if you could replace the content in your file `coursedata/hw1-snaqTimeTests/readme.md`. Right now, the content is the description of the problem. If you could replace it by an explanation of your solution, it would be helpful: say where the different files are, where to run the scripts from, how to run each script (copy-paste the command you used), what files they produce, etc.

You have 2 output files: `csv` and `morton.hw1.csv`. I had to look at their content to guess which one is the good one. I suggest that you remove the other, with this: `git rm csv` (run from `coursedata/hw1-snaqTimeTests/` as the current directory), then commit this change.
