### ISSUE TITLE
Mark homework 1, exercise 3 of William-Morton

### ISSUE THREAD

**Issue by mortonwilliam** [mortonwilliam/stat679work#2]
8cd6676c

@cecileane 

hi, here is part three of the homework. I was not sure you wanted the whole code below but just in case! here it is (some parts are still not the best).

``` shell

echo basename, hmax, CPUtime, Nruns, Nfail, fabs, frel, xabs, xrel, Seed, under3460, under3450, under3440 >> wmortonhw1.csv
for filename in log/*.log
do

  Basename=$(echo "${filename}" | grep -o -E "[^/]+$" | grep -o -E "^[^.]+")
  #gives filenames
  Hmax=$(grep -E -o 'hmax = [0-9]+' log/${Basename}.log | head -n 1 | grep -E -o '\d+')
  #hmax values from log files
  CPUTime=$(grep -E -o 'Elapsed time. \d+\.\d+' out/${Basename}.out | grep -E -o '\d+\.\d+')
  #gives all digits for CPUTime before and then after "."
  Nruns=$(sed -n 'runs = [0-9]+' $filename | tail -n 1  | grep -o -E '\d+')
  #"max number of failed proposals"
  #still can get this one to work?
  Nfail=$(sed -n '5p' $filename | grep -o -E 'proposals\s=\s\d+' | grep -o -E "\d+")
  #max number of failed proposals
  Seed=$(grep "main seed" $filename  | grep -E -o "\d+")
  #main seed/seed for the first runs
  frel=$(sed -n '3p' $filename | cut -f4 -d" " | grep -E -o "\d+.+\d+")
  #ftolRel for each analysis
  fabs=$(sed -n '3p' $filename | cut -f5 -d" " | grep -E -o "\d+.+\d+")
  #ftolAbs in the log file
  xabs=$(sed -n '4p' $filename | cut -f1 -d "," | grep -E -o "\d+.+\d+")
  #xtolABS for each analysis
  xrel=$(sed -n '4p' $filename | cut -f2 -d "," | grep -E -o "\d+.+\d+")
  #xtolRel for each analysis

loglik=$(grep "loglik of best" $filename | cut -f10 -d " " | cut -f1 -d.)
i1=5000
i2=5000
i3=5000
for lik in $loglik
do
  if [ $lik -lt 3460 ]
  then
    echo "i is less than 5000"
  fi

  if [ $lik -lt 3450 ]
  then
    echo "i is less than 5000"
  fi

  if [ $lik -lt 3440 ]
  then
  echo "i is less than 5000"
  fi
done
#loops still dont work
  echo "$Basename, $Hmax, $CPUTime, $Nruns, $Nfail, $fabs, $frel, $xabs, $xrel, $Seed, $under3460, $under3450, $under3440"  >> wmortonhw1.csv
done

```

**done**!

**Comment by cecileane** [comment]
Thanks William! This is my way of asking Maria (@mkamenet3) and Zach (@kingcohn1) to try your script and provide feedback on it.

**Comment by mkamenet3** [comment]
@mortonwilliam 

Hi William!

I was wondering if it may be helpful to change the folder structure a little for upcoming assignments. So right now you have the scripts and folders containing the raw data files on the same levels in the 'hw1-snaqTimeTests' folder which is in the 'coursedata' folder. It may be nice to have something like: stat679work -> coursedata, scripts, output, etc (multiple folders). Then you can maybe move the scripts into 'scripts' and call the files from the 'hw1-snaqTimeTests' folder as needed. I had my scripts in the 'hw1-snaqTimeTests' folder as well and then changed the directory structure too. This also may help clarify which data is the input data and which is the output data (although this can instead also be clarified in the readme).

In the readme in the 'hw1-snaqTimeTests' folder, it may be nice to include the code of how to run the scripts (the specific call) and if there is an order the scripts should be called in. 

In 'normalizeFileNames.sh', I really liked how you included an echo statement so it prints at each iteration so you know it's working. 

In 'summarizeSNaQres.sh', it may be helpful to include:

```
#!/bin/bash
set -e
set -u
set -o pipefail
```

at the beginning of the script.  Additionally, as I was reading the script (prior to just running it), it would be helpful for the user to sprinkle in some more comments about what each of the chunks is doing. I really liked that way you utilized **Basename** in the loop and strung together a lot of different commands to extract. I wasn't sure, however, why you set i1,i2,and i3 to be equal to 5000 initially and then had the echo statement set to 5000 (although I did like having an echo statement that prints so I know everything is working).  Unfortunately, when I ran the file, 'wmortonhw1.csv' was empty, except for _Seed_ which has 'd' in the column. To run the file, I was on bash on ubuntu on windows and just used **source summarizeSNaQres.sh**.

Overall nice job! I really liked that  you kept the user in mind with the echo comments - I found that very helpful.

**Comment by zpcohen** [comment]
Hey William,

Nice work, here! As mkamenet3 mentioned, it's better to head this script with:

``` shell
#!/bin/bash
set -e # script terminates if any command exits with non-zero status
set -u # terminates if any variable is unset
set -o pipefail
```

Also, you created a variable of `$basename`, as:
`Basename=$(echo "${filename}" | grep -o -E "[^/]+$" | grep -o -E "^[^.]+")
  #gives filenames` 
rather than using the `basename` command, like: 
`Basename=$(basename -s ".log" "${filename}" | grep -o -E "[^/]+$" | grep -o -E "^[^.]+")
  #gives filenames`

I like your use of grep, sed, and cut.  However, I had issues getting the proper outputs for each variable. Like, mkamenet3, the .csv file was empty except for iterative "d"s in the seed column. The `if` statement is problematic. Why does it echo "i is less than 5000" for each if loop? I think you wanted to determine which tests are greater than 3460 by setting the variables of the tests to 5000 and then adding 1? So, if they are more than 3460 they won't be less than 5000? Anyway, this is a dizzying approach to a simple command. I first suggest setting the loglik variable, as you did, and then setting each test variable i=0, not=5000. You also need to ask the if command to do something _if_ the variable doesn't match your criterion ie <3460. Here, we want to count the runs that are less than these values by setting the i variable to 0 and then adding 1 if it passes the if statement. Try:

``` shell
loglik=$(grep "loglik of best" $filename | cut -f10 -d " " | cut -f1 -d.) #fine use of variable set
i1=0
i2=0
i3=0
for lik in $loglik # now the for loop will call my variables $loglik from previous grep
do
  if [ $lik -lt 3460 ] #now we test if these values are less than 3460 (nnnn)
  then
  i1=$((i1+1))   # we reset our i1 variable to give a value of 1 for every number passing our if statement (0+1), doing this iteratively will sum up the total number of tests that pass our if statement.
echo $i1 # here you can echo to see how many of runs, in all of our data sets, pass the test! 
  fi 
```

**Comment by cecileane** [comment]
Thank you Zach for your suggestions! William: try what Zach suggests with the `i1`, `i2` and `i3` counters. I think it should work. You'll need to print the final `i1`, `i2` and `i3` values in the summary file in the end.

Regarding Basename, an even simpler solution would be this:

``` shell
Basename=$(basename -s ".log" "${filename})"
```
